# 数据源配置
spring:
    jpa:
      database: MYSQL
      show-sql: false
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      format-sql: true
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      data-username: root
      data-password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        min-idle: 10
        max-active: 20
        initial-size: 5
        validation-query: select 1
  # Redis数据源
    redis:
      host: localhost
      port: 6379
      timeout: 6000
      password:       # 连接池中的最小空闲连接
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5

