version: '2'
services:
    mysql:
      container_name: mysql
      image: mysql:5.7
      ports:
        # 端口映射
        - 3306:3306
      restart: always
      environment:
        MYSQL_DATABASE: test
        MYSQL_ROOT_PASSWORD: root
      volumes:
        # 目录映射
        - ./mysql/my.cnf:/etc/mysql/my.cnf
        - ./mysql/datadir:/var/lib/mysql
      networks:
        - shiro
    redis:
      # 指定镜像
      image: redis:5
      container_name: redis
      restart: "always"
      ports:
        # 端口映射
        - 6379:6379
      networks:
        - shiro
      volumes:
        # 目录映射
        - ./redis/conf:/usr/local/etc/redis
        - ./redis/data:/data
      command:
        # 执行的命令
        redis-server
    shiro:
      image: cosmos-shiro:latest
      ports:
        - 8764:8764
      restart: "always"
      container_name: "shiro" 
      depends_on:
        - mysql
        - redis
      networks:
        - shiro
    
    
networks:
  shiro:
   driver: bridge
